import type { PlanInput, PlanOutput } from "./schema";
import { hhmmToMinutes, localWallClockToUTC, utcToLocalParts } from "./time";

/**
 * Server-side validation of a PlanOutput against the user's PlanInput.
 *
 * Returns either enriched sessions ready for insertion (with resolved
 * topicId, startsAtUTC, endsAtUTC), or a single human-readable error
 * describing why the plan is unusable. Per API.md, the caller retries
 * once on failure with an addendum, then surfaces the error to the user.
 */

const MIN_BREAK_MINUTES = 5;

export type ValidatedSession = {
  topicId: string;
  subjectName: string;
  topicName: string;
  instruction: string;
  durationMinutes: number;
  startsAtUTC: Date;
  endsAtUTC: Date;
};

export type ValidationResult =
  | { ok: true; sessions: ValidatedSession[]; warnings: PlanOutput["warnings"] }
  | { ok: false; error: string };

/** Normalise a subject/topic name for fuzzy matching: trim + lowercase. */
function norm(s: string): string {
  return s.trim().toLowerCase();
}

/**
 * Sessions generated by the LLM can be off by a few minutes due to prompt
 * ambiguity about "right now". Allow a 3-minute grace window before rejecting
 * a session as "in the past".
 */
const PAST_GRACE_MS = 3 * 60_000;

export function validatePlanOutput(
  input: PlanInput,
  output: PlanOutput,
  latestExamDate: string | null,
): ValidationResult {
  // Build lookup maps using normalised keys so the LLM's minor casing/spacing
  // variants ("Physics " vs "Physics") don't cause unnecessary failures.
  const subjectByName = new Map(
    input.subjects.map((s) => [
      norm(s.name),
      { name: s.name, examDate: s.examDate, topics: new Map(s.topics.map((t) => [norm(t.name), t.id])) },
    ]),
  );

  const availByDay = new Map<number, Array<{ startsAt: number; endsAt: number }>>();
  for (const w of input.availability) {
    const list = availByDay.get(w.dayOfWeek) ?? [];
    list.push({ startsAt: hhmmToMinutes(w.startsAt), endsAt: hhmmToMinutes(w.endsAt) });
    availByDay.set(w.dayOfWeek, list);
  }

  const validated: ValidatedSession[] = [];
  const nowUTC = input.now.getTime();

  for (const s of output.sessions) {
    // 1. subjectName exists (normalised lookup — handles extra spaces, case)
    const subj = subjectByName.get(norm(s.subjectName));
    if (!subj) {
      return { ok: false, error: `Unknown subject "${s.subjectName}" in plan output.` };
    }
    // 2. topicName exists under that subject (normalised lookup)
    const topicId = subj.topics.get(norm(s.topicName));
    if (!topicId) {
      return {
        ok: false,
        error: `Topic "${s.topicName}" is not under subject "${s.subjectName}".`,
      };
    }
    // 3. duration matches user's chosen session length
    if (s.durationMinutes !== input.sessionLengthMinutes) {
      return {
        ok: false,
        error: `Session duration ${s.durationMinutes} does not match chosen ${input.sessionLengthMinutes} min.`,
      };
    }

    // 4. startsAt parses as local wall clock and converts to UTC
    let startsAtUTC: Date;
    try {
      startsAtUTC = localWallClockToUTC(s.startsAt, input.timeZone);
    } catch {
      return { ok: false, error: `Invalid startsAt "${s.startsAt}".` };
    }
    const endsAtUTC = new Date(startsAtUTC.getTime() + s.durationMinutes * 60_000);

    // 5. session is in the future (3-minute grace for prompt-to-execution lag)
    if (startsAtUTC.getTime() < nowUTC - PAST_GRACE_MS) {
      return {
        ok: false,
        error: `Session ${s.startsAt} · ${s.subjectName} is in the past.`,
      };
    }

    // 6. session date is <= latest exam date (if any subject has one)
    if (latestExamDate) {
      const localStart = utcToLocalParts(startsAtUTC, input.timeZone);
      if (localStart.dateString > latestExamDate) {
        return {
          ok: false,
          error: `Session on ${localStart.dateString} is after the last exam date ${latestExamDate}.`,
        };
      }
    }

    // 7. session fits inside an availability window on the correct day
    const localStart = utcToLocalParts(startsAtUTC, input.timeZone);
    const localEnd = utcToLocalParts(endsAtUTC, input.timeZone);
    if (localStart.dateString !== localEnd.dateString) {
      return {
        ok: false,
        error: `Session ${s.startsAt} crosses midnight; sessions must fit in one day.`,
      };
    }
    const windows = availByDay.get(localStart.dayOfWeek);
    const fits = windows?.some(
      (w) =>
        localStart.minutesInDay >= w.startsAt &&
        localStart.minutesInDay + s.durationMinutes <= w.endsAt,
    );
    if (!fits) {
      return {
        ok: false,
        error: `Session ${s.startsAt} does not fit inside any availability window.`,
      };
    }

    validated.push({
      topicId,
      subjectName: subj.name,
      topicName: s.topicName,
      instruction: s.instruction,
      durationMinutes: s.durationMinutes,
      startsAtUTC,
      endsAtUTC,
    });
  }

  // 8. no overlaps between sessions, with a >= MIN_BREAK_MINUTES gap for
  //    consecutive same-day sessions.
  const sorted = [...validated].sort(
    (a, b) => a.startsAtUTC.getTime() - b.startsAtUTC.getTime(),
  );
  for (let i = 1; i < sorted.length; i++) {
    const prev = sorted[i - 1];
    const curr = sorted[i];
    if (curr.startsAtUTC.getTime() < prev.endsAtUTC.getTime()) {
      return {
        ok: false,
        error: `Session at ${curr.startsAtUTC.toISOString()} overlaps a previous session.`,
      };
    }
    const prevLocal = utcToLocalParts(prev.startsAtUTC, input.timeZone);
    const currLocal = utcToLocalParts(curr.startsAtUTC, input.timeZone);
    if (prevLocal.dateString === currLocal.dateString) {
      const gapMs = curr.startsAtUTC.getTime() - prev.endsAtUTC.getTime();
      if (gapMs < MIN_BREAK_MINUTES * 60_000) {
        return {
          ok: false,
          error: `Consecutive same-day sessions need at least a ${MIN_BREAK_MINUTES}-min break.`,
        };
      }
    }
  }

  // 9. No session may overlap a Google Calendar busy period.
  //    All comparisons are in UTC to avoid timezone/DST ambiguity.
  if (input.calendarBusyPeriods && input.calendarBusyPeriods.length > 0) {
    for (const session of sorted) {
      for (const busy of input.calendarBusyPeriods) {
        const busyStart = new Date(busy.startsAt).getTime();
        const busyEnd = new Date(busy.endsAt).getTime();
        const overlaps =
          session.startsAtUTC.getTime() < busyEnd &&
          session.endsAtUTC.getTime() > busyStart;
        if (overlaps) {
          return {
            ok: false,
            error: `Session "${session.subjectName} · ${session.topicName}" at ${session.startsAtUTC.toISOString()} conflicts with a Google Calendar event (${busy.startsAt}–${busy.endsAt}).`,
          };
        }
      }
    }
  }

  return { ok: true, sessions: sorted, warnings: output.warnings };
}

/** Warnings whose subjectName+topicName don't exist are dropped; safer than surfacing garbage. */
export function sanitizeWarnings(
  input: PlanInput,
  warnings: PlanOutput["warnings"],
): PlanOutput["warnings"] {
  const knownSubjects = new Map(
    input.subjects.map((s) => [s.name, new Set(s.topics.map((t) => t.name))]),
  );
  return warnings.filter((w) => {
    const topics = knownSubjects.get(w.subjectName);
    return topics ? topics.has(w.topicName) : false;
  });
}

/** Compute the latest exam date across all subjects, or null. */
export function latestExamDateOf(input: PlanInput): string | null {
  let latest: string | null = null;
  for (const s of input.subjects) {
    if (s.examDate && (latest === null || s.examDate > latest)) latest = s.examDate;
  }
  return latest;
}

/** Increment a YYYY-MM-DD date string by n days. */
function addDaysStr(dateStr: string, n: number): string {
  const d = new Date(dateStr + "T12:00:00Z");
  d.setUTCDate(d.getUTCDate() + n);
  return d.toISOString().slice(0, 10);
}

/**
 * Pre-flight feasibility check, run BEFORE calling the LLM.
 *
 * Exams are NOT required — students may have tasks-only, or no deadlines at
 * all. The planning horizon is max(future exam date, future task due date,
 * 28 days), so there is always a window to plan into.
 *
 * Returns an actionable error only for hard impossibilities: windows too short
 * to fit a session, or (very rarely) zero slots in a sub-7-day horizon.
 */
export function checkPlanFeasibility(
  input: PlanInput,
): { ok: true } | { ok: false; error: string } {
  const todayLocal = utcToLocalParts(input.now, input.timeZone);
  const todayDateStr = todayLocal.dateString;

  // 1. At least one availability window must be long enough for a single
  //    session. If every window is shorter than the session length, no
  //    session can ever fit.
  const longestWindow = input.availability.reduce((max, w) => {
    const len = hhmmToMinutes(w.endsAt) - hhmmToMinutes(w.startsAt);
    return len > max ? len : max;
  }, 0);
  if (longestWindow < input.sessionLengthMinutes) {
    return {
      ok: false,
      error: `Your available time blocks are shorter than your ${input.sessionLengthMinutes}-minute sessions. Add a longer window or choose a shorter session length.`,
    };
  }

  // 2. Determine the planning horizon.
  //    Exams are optional. Horizon = max(future exam, future task due date, 28 days).
  //    The 28-day default guarantees we always have a window to plan into.
  const futureExam =
    input.subjects
      .map((s) => s.examDate)
      .filter((d): d is string => d != null && d > todayDateStr)
      .sort()
      .pop() ?? null;

  const latestTaskDue =
    (input.tasks ?? [])
      .map((t) => t.dueDate)
      .filter((d): d is string => d != null && d > todayDateStr)
      .sort()
      .pop() ?? null;

  const defaultHorizon = addDaysStr(todayDateStr, 28);
  const horizon =
    [futureExam, latestTaskDue, defaultHorizon]
      .filter((d): d is string => d != null)
      .sort()
      .pop() ?? defaultHorizon;

  // 3. At least one availability window occurrence must actually fall between
  //    now and the horizon with enough room for a full session.
  //    Because the horizon is always ≥ 28 days, daysToHorizon ≥ 28 ≥ 7,
  //    so the early-return below almost always fires. The walk remains as a
  //    safety net for pathological inputs.
  const todayMinutes = todayLocal.minutesInDay;
  const windowsByDOW = new Map<number, Array<{ startsAt: number; endsAt: number }>>();
  for (const w of input.availability) {
    const list = windowsByDOW.get(w.dayOfWeek) ?? [];
    list.push({ startsAt: hhmmToMinutes(w.startsAt), endsAt: hhmmToMinutes(w.endsAt) });
    windowsByDOW.set(w.dayOfWeek, list);
  }

  // Use local noon as the anchor — avoids UTC-offset calendar drift on UTC+12+ zones.
  const todayDate = localWallClockToUTC(todayDateStr + "T12:00", input.timeZone);
  const horizonDate = localWallClockToUTC(horizon + "T12:00", input.timeZone);
  const daysToHorizon = Math.round((horizonDate.getTime() - todayDate.getTime()) / 86_400_000);

  // ≥7 days guarantees every day-of-week appears at least once; check 1
  // confirmed a sufficient-length window exists, so feasibility is certain.
  if (daysToHorizon >= 7) return { ok: true };

  // Short-range walk: only reachable if all of exam, task, and default horizons
  // fall within 7 days (effectively impossible with the 28-day default).
  let hasFeasibleSlot = false;
  for (let d = 0; d <= daysToHorizon && !hasFeasibleSlot; d++) {
    const dayDate = new Date(todayDate.getTime() + d * 86_400_000);
    const { dayOfWeek } = utcToLocalParts(dayDate, input.timeZone);
    const windows = windowsByDOW.get(dayOfWeek);
    if (!windows) continue;
    hasFeasibleSlot = windows.some((w) => {
      if (d === 0) {
        return w.endsAt - input.sessionLengthMinutes >= todayMinutes;
      }
      return w.endsAt - w.startsAt >= input.sessionLengthMinutes;
    });
  }

  if (!hasFeasibleSlot) {
    return {
      ok: false,
      error: "No study slots fit in your current schedule. Add more available time.",
    };
  }

  return { ok: true };
}
