# Multi-stage Next.js production image.
# Stage 1: install deps
# Stage 2: build
# Stage 3: minimal runtime (~200MB vs ~1GB for a full install)
#
# Requires next.config.ts to have output: 'standalone'.
# Usage:
#   docker build -t pace .
#   docker run -p 3000:3000 --env-file .env.docker pace

FROM node:22-alpine AS base

# ── Stage 1: install dependencies ────────────────────────────────────────────
FROM base AS deps
# libc6-compat: needed by some native Node.js modules on Alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# ── Stage 2: build ───────────────────────────────────────────────────────────
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Disable Next.js telemetry during build.
ENV NEXT_TELEMETRY_DISABLED=1

# Build args become env vars at build time.
# NEXT_PUBLIC_* vars must be present at build time because Next.js inlines them.
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY

RUN npm run build

# ── Stage 3: production runner ────────────────────────────────────────────────
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Non-root user for security.
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Copy only the standalone output (does not need node_modules at runtime).
# The standalone output is self-contained: it includes only the required
# server-side dependencies copied in from node_modules during the build.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static     ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# server.js is generated by Next.js when output: 'standalone' is set.
CMD ["node", "server.js"]
